#!/usr/bin/env sh
set -eu

ROOT_DIR="$(git rev-parse --show-toplevel)"
"$ROOT_DIR/scripts/bump_version.sh"

cp "$ROOT_DIR/VERSION" "$ROOT_DIR/client/VERSION"
cp "$ROOT_DIR/VERSION" "$ROOT_DIR/server/VERSION"

git add "$ROOT_DIR/VERSION" "$ROOT_DIR/client/VERSION" "$ROOT_DIR/server/VERSION"
